---
    # handlers file for jenkins-maven-docker
    
      - name: Ensure Jenkins is started and runs on startup.
        service: 
          name: jenkins
          state: started 
          enabled: yes
    